CONFIG = {
    "data_not_present":{
      "not_available":"N/A"
    },
    "available_classes":["Email","Broker Presentation", "Confirmed Claims Experience","Vehicle Schedule","Haulage Fact Finder"],
    "class_priority_lists":{
      "default":["Email","Broker Presentation", "Confirmed Claims Experience","Vehicle Schedule", "Haulage Fact Finder"],
      "cce":["Confirmed Claims Experience"],
      "CP2":["Broker Presentation", "Confirmed Claims Experience","Email"],
      "CP3":["Broker Presentation", "Confirmed Claims Experience","Email","Vehicle Schedule"],
      "CP4":["Broker Presentation","Email", "Confirmed Claims Experience","Vehicle Schedule"],
      "CP5":["Broker Presentation","Email","Vehicle Schedule"],
      "CP6":["Broker Presentation","Vehicle Schedule","Email"],
      "CP7":["Confirmed Claims Experience","Vehicle Schedule","Email"],
      # "CP8":["Confirmed Claims Experience","Broker Presentation","Email"],
      "CP8":["Broker Presentation","Confirmed Claims Experience","Email"],
      "CP9":["Confirmed Claims Experience","Broker Presentation","Vehicle Schedule","Email"],
      "CP10":["Confirmed Claims Experience","Broker Presentation"],
      "email":["Email"],
      "CP11":["Email","Broker Presentation"],
      "haulage":["Haulage Fact Finder"],
      "CP12":["Vehicle Schedule", "Broker Presentation","Email"],
      "CP13":["Broker Presentation", "Email"]
    },
    "fields":{
      "Business_Description":{
          "human_review":True,
          "class_priority":"CP2",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Expires_On":{
          "human_review":True,
          "class_priority":"CP2",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "AXA_Trade_Description":{
          "human_review":True,
          "class_priority":"CP2",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Effective_To":{
          "human_review":True,
          "class_priority":"CP2",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
       "Risk_Postcode":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_Line_1":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_Line_2":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_Line_3":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_Country":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_State":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_City":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Party_Address_Postcode":{
          "human_review":True,
          "class_priority":"CP3",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Company_House_Reference_Party":{
          "human_review":True,
          "class_priority":"CP13",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Date_Established":{
          "human_review":True,
          "class_priority":"CP13",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Is_Holding_Broker":{
          "human_review":True,
          "class_priority":"CP13",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Driver_Party_Table":{
          "human_review":True,
          "class_priority":"CP13",
          "table":True,
          "empty":"not_available",
          "intra_merge_type":"concat",
          "sep":",",
          "merge_type":"replace"
        },
        "Agency_address":{
          "human_review":True,
          "class_priority":"CP13",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Insured":{
          "human_review":True,
          "class_priority":"CP4",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Offering_Type":{
          "human_review":True,
          "class_priority":"CP5",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Number_Of_Years_Cliams_Experience":{
          "human_review":True,
          "class_priority":"cce",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Incepts_On":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Effective_From":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Main_Cover_Type":{
          "human_review":True,
          "class_priority":"CP9",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Main_Cover_Type_Mapped":{
          "human_review":True,
          "class_priority":"CP9",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Excess_Type_Accident_Damage":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Excess_Type_Fire":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Excess_Type_Theft":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Excess_Type_WS":{
          "human_review":True,
          "class_priority":"CP8",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "CCE_Table":{
          "human_review":True,
          "class_priority":"CP10",
          "table":True,
          "empty":"not_available",
          "intra_merge_type":"concat",
          "sep":",",
          "merge_type":"replace"
        },
        "Agency_Code":{
          "human_review":True,
          "class_priority":"email",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Agency_Contact":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Agency_Name":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Product":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Broker_Deadline":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Agency_Enquiry_Reference":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Target_Price":{
          "human_review":True,
          "class_priority":"CP11",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Haulage_Fact_Finder_received":{
          "human_review":True,
          "class_priority":"haulage",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Number_of_Notifiable_Vehicles":{
          "human_review":True,
          "class_priority":"CP12",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Vehicle_Registration":{
          "human_review":True,
          "class_priority":"CP12",
          "table":False,
          "empty":"not_available",
          "intra_merge_type":"replace",
          "sep":",",
          "merge_type":"replace"
        },
        "Vehicle_Schedule_Table":{
          "human_review":True,
          "class_priority":"CP12",
          "table":True,
          "empty":"not_available",
          "intra_merge_type":"concat",
          "sep":",",
          "merge_type":"replace"
        }
    },
    "hidden":["Effective_From","Effective_To","Unique_Values_Cover_Basis","Unique__Values__Cover__Basis", "Driver_Data_Merged", "Todays_Date", "Vehicle_Count_From_Table", "Year", "Claims_Period", "Vehicle_Registration_Numbers_And_Cover_Basis", "Driver_Name_And_Driver_DOB", "Cover_Basis_Mapping", "Conviction_Code", "Drive_Type", "Driver_Details", "Vehicle_Count_From_Email", "Driver_Merged_Data", "Vehicle_Schedule_Data", "Driver_Licence_Tenure", "Policy_Dates", "Driver_Name_And_Licence_Date_Info", "Holding_Broker", "Unique_Values_in_Cover_On_Policy", "Conviction_Details", "Today_date", "cover_mapping", "Cover_Mapping_For_CCE_Table", "Excess_and_Claims_List", "Excess_List", "Vehicle_Category_Info_and_Registration_Numbers", "Period", "Driver_Age", "Unique_Values_In_Cover_Vehicle_CCE", "CCE_Data", "Insurer_Data", "Driver_Type"],
    "default_field_config":{
        "human_review":True,
        "class_priority":"default",
        "table":False,
        "empty":"not_available",
        "merge_type":"replace",
        "intra_merge_type":"replace"
    }
  }


FORMAT_CONFIG = {
  "HITL_Fields":{
    "Number":[
    ["Target_Price", False, -1]
    ],
    "Text":[]
  },
  "Table":{
    "Number":[["Excess: AD",False,-1], ["Excess: Fire",False,-1],["Excess: WS",False,-1],["Excess: Theft",False,-1] , ["Claim Count: All",True,-1], ["Incurreds - Paid: AD&WS",True,-1],
      ["Incurreds - Paid: FT",True,-1], ["Incurreds - Paid: TP",True,-1], ["Incurreds - Outstanding: AD&WS",True,-1], ["Incurreds - Outstanding: FT",True,-1], ["Incurreds - Outstanding: TP",True,-1],
      ["Claim Count: WS", True, -1], ["Total Incurred Paid + Outstanding", True, -1]
    ],
    "Text":[
      ["Effective From",False,False,True,False,[[r"\bN/A\b",""], [r"\bn/a\b",""]]], 
      ["Effective To",False,False,True,False,[[r"\bN/A\b",""], [r"\bn/a\b",""]]],
      ["Cover - Vehicle",False,False,True,False,[[r"\bN/A\b",""], [r"\bn/a\b",""]]],
      ["Cover - Vehicle - Mapped",False,False,True,False,[[r"\bN/A\b",""], [r"\bn/a\b",""]]],
      ["Conviction Details",False,False,True,False,[[r"No|no",""]]],
      ["Vehicle Registration", True, False, True, False,[[r"\s+",""]]],
      ['Driver: Years Appropriate Licence Held',False, False,True,False,[[r"\b(?:[6-9]|\d{2,})\b", "5+"]]]
    ]
  }
}

# use column names for the formatting of tables.